---
title: "Retards sur les liaisons TGV de la SNCF"
author: "(P. Cottais & E. Hermance)"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Données :", align: right }
      - { icon: "fa-train", href: "https://www.kaggle.com/gatandubuc/public-transport-traffic-data-in-france", align: right }
      - { icon: "fa-map", href: "https://www.data.gouv.fr/en/datasets/gares-tgv-en-france/", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color: #0088CE;
  border-color: #0088CE;
}
.navbar-brand {
color: white!important;
}

.fa {
  color: white;
}

.navbar-inverse .navbar-nav > li > a {
    color: white;
}

.navbar-inverse .navbar-nav > li > a:hover {
    color: white;
}


</style>   


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(flexdashboard)
library(readr)
library(tidyverse)
library(plotly)
library(maps)
library(geosphere)
library(mapproj)
library(sp)
library(sna)
library(GGally)
```



```{r data, eval = TRUE, echo = FALSE, results='hide', message = FALSE, warning=FALSE}
train <- read_csv("data/Regularities_by_liaisons_Trains_France.csv")
coord <- read_delim("data/Coordonnees.csv", delim = ";", escape_double = FALSE,
                    trim_ws = TRUE)

# add  a d season fields
train <- train %>% 
  mutate(
    # % of late trains (on arrival)
    Percent_trains_late = `Number of trains late on arrival`/
           (`Number of expected circulations`-`Number of cancelled trains`),
    # Season from month
    Season = case_when(Month %in% 2:4 ~ "A",
                            Month %in% 5:7 ~ "B",
                            Month %in% 8:10 ~ "C",
                            Month %in% c(11, 12, 1) ~ "D"),
    # Number of late trains on arrival by reason
    Nb_late_external_causes = `Number of trains late on arrival`*`% trains late due to external causes (weather, obstacles, suspicious packages, malevolence, social movements, etc.)`,
    Nb_late_infrastructure = `Number of trains late on arrival`*`% trains late due to railway infrastructure (maintenance, works)`,
    Nb_late_traffic_mgmt = `Number of trains late on arrival`*`% trains late due to traffic management (rail line traffic, network interactions)`,
    Nb_late_rolling_stock = `Number of trains late on arrival`*`% trains late due to rolling stock`,
    Nb_late_station_mgmt = `Number of trains late on arrival`*`% trains late due to station management and reuse of material`,
    Nb_late_passengers = `Number of trains late on arrival`*`% trains late due to passenger traffic (affluence, PSH management, connections)`
  )

month.name.fr <- c("Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet",
                   "Août", "Septembre", "Octobre", "Novembre", "Décembre")
season.name.fr <- c("Printemps", "Été", "Automne", "Hiver")

```


Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

L'objectif de ce tableau de bord est d'identifier les zones les plus sujettes au retard des TGV afin de comprendre les raisons de ces différences inter-zone. Ces zones sont les destinations au départ de Paris, point central de la France jacobine acutelle.


### Carte centralisée des liaisons par zone

```{r map, echo=FALSE, message=FALSE, warning=FALSE}
e_train <- train %>% select(`Departure station`, `Arrival station`,
                            `Number of expected circulations`) %>% 
  rename(Dep = `Departure station`, Arr = `Arrival station`) %>% 
  group_by(Dep, Arr) %>% 
  summarise(Nb = sum(`Number of expected circulations`, na.rm = TRUE))

# nodes: stations
y_train <- as.data.frame(coord) %>% filter(`Departure station` %in% e_train$Dep |
                              `Departure station` %in% e_train$Arr) %>% 
  rename(Station = `Departure station`)

test <- map_data("world") %>% 
  filter(region %in% c("France", "Belgium", "Luxembourg", "Germany", "Spain", "Portugal", "Switzerland", "Italy"))

e_train <- e_train %>% 
  filter(str_detect(Dep,"PARIS")|str_detect(Arr,"PARIS"))

# convert to network
sens <- network(e_train, directed = TRUE,loops = TRUE)

rownames(y_train) <- y_train$Station

# add geographic coordinates
sens %v% "lat" <- y_train[network.vertex.names(sens),"Latitude"]
sens %v% "lon" <- y_train[network.vertex.names(sens),"Longitude"]

# drop isolated airports
delete.vertices(sens, which(degree(sens) < 2))

# compute degree centrality
sens %v% "degree" <- degree(sens, gmode = "graph")

# add random groups
sens %v% "mygroup" <- y_train[network.vertex.names(sens),"Direction"]

# create a map of the USA
europa <- ggplot(test, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), color = "grey65",
               fill = "#f9f9f9", size = 0.2) +  
  coord_map(xlim = c(-5, 10.5),ylim = c(40, 51))

# overlay network data to map
map <- ggnetworkmap(europa, net = sens, size = 10, great.circles = TRUE,
             segment.color = "steelblue", arrow.size = 0,
             node.group = mygroup, alpha = 1,
             ring.group = degree, weight = degree, legend)
map
```



Column {data-width=500}
-----------------------------------------------------------------------

### Évolution saisonnière des retards

```{r graph1, echo=FALSE, message=FALSE, warning=FALSE, fig.height=4, fig.width=9}
# Évolution saisonnière des retards
ggp1 <- train %>% 
  filter(str_detect(`Departure station`, "PARIS")) %>% 
  left_join(coord, by = c("Arrival station" = "Departure station")) %>% 
  group_by(Season, Direction) %>% 
  summarise(Retards = mean(Percent_trains_late, na.rm = TRUE)) %>%
  # diagramme en barres
  ggplot() + aes(x = Season, y = Retards*100, fill = tolower(Direction)) +
  geom_bar(stat = "identity", position='dodge', width = 0.5) +
  # scale_colour_colorblind() +
  scale_x_discrete(labels = season.name.fr) +
  ylab(element_blank()) + xlab(element_blank()) +
  labs(title = "Trains en retards à la gare d'arrivée (en %)",
       caption = "Période : janvier 2015 à juin 2020") +
  theme(plot.title = element_text(size = 12, face = "bold.italic", hjust = 0.5),
        plot.caption = element_text(size = 8, face = "italic", hjust = 1),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.text.x = element_text(vjust = 0.5),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = 'grey', linetype = 'dotted'),
        panel.grid.major.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_fill_brewer(palette="Paired")  # colorblind -friendly palette
  # scale_fill_brewer(palette="Dark2")
ggp1
```


### Évolution saisonnière des motfis de retard

```{r}

```

